
parameters:
    aerial_ship_saml_sp.state.store.sso.class: AerialShip\SamlSPBundle\Doctrine\SSOStateStore
    aerial_ship_saml_sp.backend_type_mongodb: 1

services:
    # factory will be set in bundle extension, listed here to be used as a reference in other services
    aerial_ship_saml_sp.document_manager:
        class: Doctrine\ODM\MongoDB\DocumentManager
        arguments:
            - %aerial_ship_saml_sp.model_manager_name% # not realy used since factory is set in extension
        public: false

    aerial_ship_saml_sp.state.store.sso:
        class: %aerial_ship_saml_sp.state.store.sso.class%
        arguments: [%aerial_ship_saml_sp.state.store.sso.entity_class%, @aerial_ship_saml_sp.document_manager]
        public: false
